main: me.hypersmc.jumpwatch.worlds.Main
name: Worlds
version: 0.0.1
api-version: 1.13
description: Worlds is a Gamemode for servers that want a story with sidemissions. Worlds includes premade story with over 100 side quests and 50 main missions.
depend:
  - Citizens
  - WorldEdit
  - AsyncWorldEdit
  - WorldGuard
  - 'Multiverse-Core'

authors:
  - JumpWatch
  - HypersMC
  - Contributors
commands:
  WorldsA:
    description: Admin side of Worlds
    permission: Worlds.Admin.Use
    usage: /<command>
  Worlds:
    description: User side of Worlds
    permission: Worlds.Use
    usage: /<command>