main: me.hypersmc.jumpwatch.worlds.Main
name: Worlds
version: 0.0.1
api-version: 1.13
description:
default-permission: worlds.use
depend:
  - Citizens
  - WorldEdit
  - AsyncWorldEdit
  - WorldGuard
  - multiversecore

authors:
  - JumpWatch
  - HypersMC
commands:
  WorldsA:
    description: Admin side of Worlds
    permission: Worlds.Admin.Use
    usage: /<command>